=== arroyosergi3/EjerciciosLMSGI/cocteleria.dtd
<!ELEMENT cocteleria ANY >
<!ELEMENT cocteles (coctel+)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT coctel (nombre, alcohol?, precio, (existencias | agotado))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT alcohol EMPTY>
<!ELEMENT precio EMPTY>
<!ELEMENT existencias EMPTY>
<!ELEMENT agotado EMPTY>
<!ELEMENT oferta (#PCDATA | coctelReferido)*>
<!ELEMENT coctelReferido ANY>
<!ATTLIST cocteleria direccion CDATA #IMPLIED nombre CDATA #REQUIRED telefono CDATA #FIXED "695456895">
<!ATTLIST coctel codigoBebida ID #REQUIRED bebidaPrincipal (vodka | ginebra | Ron) "Ron">
<!ATTLIST coctelReferido codigoBebida IDREF #REQUIRED alcoholCombinado IDREFS #IMPLIED>
<!ENTITY % atributoCoste "coste CDATA #IMPLIED">
<!ATTLIST precio %atributoCoste;>
<!ATTLIST pferta %atributoCoste;>
<!ENTITY azucar "azucar extra">

=== arroyosergi3/EjerciciosLMSGI/cocteleria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cocteleria SYSTEM "cocteleria.dtd">
<cocteleria nombre="CoctelerÃ­a Paco" >
    <cocteles>
        <coctel codigoBebida="cocoloco" bebidaPrincipal="Ron">
            <nombre>Coco Loco</nombre>
            <alcohol/>
            <precio coste="10"/>
            <existencias/>
        </coctel>
        <coctel codigoBebida="bloodymary" bebidaPrincipal="ginebra">
            <nombre>Bloody Mary con &azucar;</nombre>
            <alcohol/>
            <precio coste ="12"/>
            <agotado/>
        </coctel>
    </cocteles>
    <ofertas>
        <oferta>
            <coctelReferido codigoBebida="cocoloco" alcoholCombinado="Ron"/>
        </oferta>
    </ofertas>
</cocteleria>
